### PR TITLE
Minor improvements--failing so far to repro continuing-hlct-not-copie…

### PR DESCRIPTION
**Pull request by rpardee**
…d to new ivcontact bug.  Though I did create and then fix (pretty sure) a couple of other bugs.

This definitely fixes the no-blank-hlct on new ivcontacts though & I thought it might be worth merging just for that.

I got picky on some of the form view b/c I was running the generated html through htmlbeautify & tag lint & getting errors.  As always--apologies if I overstepped.

### CODE REVIEW

**Comment by rpardee** [comment]
Hey Chris,

I've got another chunk of work done--are you close to merging this & pushing whatever you've got so I can reconcile & create another pull req?

Thanks!

-Roy

**Comment by seemack** [comment]
Awesome - I'll merge it right now.

**Comment by rpardee** [comment]
Coolio--thanks!  Can you let me know when you've pushed your latest so I can pull them?

**Comment by seemack** [comment]
I hadn't planned to push my latest just yet - too much stuff that's still
broken for me to feel good about committing it.

I'm hoping to get a push out there by end of day tomorrow though.

**Comment by rpardee** [comment]
Ah, okay then.  I guess I'll wait to make the next pull request then.

**Comment by seemack** [comment]
If you have stuff you'd like out there, feel free to request a new pull - I
can merge them on my end and repost what I have tomorrow.

**Comment by rpardee** [comment]
Hmm--conflicted (so to speak!).  I'm afraid of saddling you w/tons of code
conflicts...

On Wed, Dec 23, 2015 at 1:27 PM, Christopher Mack <notifications@github.com>
wrote:

> If you have stuff you'd like out there, feel free to request a new pull - I
> can merge them on my end and repost what I have tomorrow.
>
> On Wed, Dec 23, 2015 at 1:25 PM, Roy Pardee <notifications@github.com>
> wrote:
>
> > Ah, okay then. I guess I'll wait to make the next pull request then.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/seemack/healthy-hearts-northwest-dev/pull/9#issuecomment-166992392
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seemack/healthy-hearts-northwest-dev/pull/9#issuecomment-166992615>
> .
>



-- 
Roy Pardee
http://datawranglr.com

**Pull request merged**
